# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jekyll', '~> 3.10'
gem 'jekyll-asciidoc', '~> 3.0'
gem 'jekyll-seo-tag', '~> 2.8'
gem 'jekyll-sitemap', '~> 1.4'
gem 'just-the-docs', '~> 0.7.0'
gem 'kramdown-parser-gfm', '~> 1.1'
